### ISSUE TITLE
Network error during setup of v0.3 app

### ISSUE THREAD

**Issue by GravityCore** [zadam/trilium-sender#25]
Can't setup the v0.3 of the app using http://[my_ip]:[my_port] because of a network error.

It should have been fixed in [v0.3](https://github.com/zadam/trilium-sender/releases/tag/v0.3) by #18, but the error still persists. Using Android 14.

Noticed on the app info screen of the v0.3 app that the version is still 0.2:
![v03 shows as v02](https://github.com/zadam/trilium-sender/assets/20287844/4dfbe08d-02c5-430f-8228-72ef83acbe6e)

Redacted following mentions of IP address, port number, user UID/GID and data path for security reasons.

Error from the logcat log:
```
2024-01-28 14:19:10.978 27668 27786 io.github.zadam.triliumsender E UserLoginCoroutine : Can't connect to Trilium server
java.net.UnknownServiceException: CLEARTEXT communication to [my_ip] not permitted by network security policy
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:188)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.github.zadam.triliumsender.LoginActivity$doLogin$2.invokeSuspend(LoginActivity.kt:173)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

My docker compose:
```
version: '2.1'
services:
  trilium:
    image: zadam/trilium:0.62.6
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - USER_UID=[my_UID]
      - USER_GID=[my_GID]
    ports:
      - "[my_port]:8080"
    volumes:
      - [my_path]:/home/node/trilium-data
```

**Comment by HighFlip** [comment]
When I downloaded the apk from [https://github.com/zadam/trilium-sender/releases/download/v0.3/trilium-sender-0.3.apk](url), it showed me the same thing as you on my Android system: version 0.2 and not 0.3, as well as had the same CLEARTEXT communication issue. 

I tried building the apk file from the source code instead and it worked for me.

**Comment by grotesque** [comment]
@zadam 
@HighFlip could you share the prebuild APK for me?
the uploaded one on release page is only 0.2 version. See proof below. Some mistake may have happened while uploading to releases.

![{0A67AEE6-23A3-47A2-BD38-119F9FDE2AA2}](https://github.com/user-attachments/assets/4b1c0604-160c-4e1f-8a78-9d28cf1c30a1)
